select distinct BILL.BLEI_CK,
	BILL.BLBL_BILLED_AMT, BILL.BLBL_RCVD_AMT,
	BILL.BLBL_BILLED_AMT - BILL.BLBL_RCVD_AMT as amtdue,
	max(BILL.BLBL_DUE_DT) curdt
from CMC_SBSB_SUBSC SBSB
right join CMC_BLEI_ENTY_INFO BLEI on BLEI.BLEI_BILL_LEVEL_CK = SBSB.SBSB_CK 
		and BLEI.BLEI_BILL_LEVEL = 'I'
right join CMC_BLBL_BILL_SUMM BILL on BILL.BLEI_CK = BLEI.BLEI_CK
where SBSB_ID = '902231411'
group by BILL.BLEI_CK, BLEI.BLEI_NET_DUE, BILL.BLBL_BILLED_AMT, BILL.BLBL_RCVD_AMT
order by curdt desc