SELECT VEH.VEH_ID, VEH.GRAPHIC_ID, VEH_MODIFIER.DSC, 
VEH_SUBMODEL_SERIES.SUBMODEL_ID, SUBMODEL.SUBMODEL_ID, SUBMODEL.NAME, BODY_STYLE.BODY_STYLE_ID
FROM SUBMODEL
	RIGHT OUTER JOIN VEH_SUBMODEL_SERIES 
		ON SUBMODEL.SUBMODEL_ID = VEH_SUBMODEL_SERIES.SUBMODEL_ID
	RIGHT OUTER JOIN VEH 
		ON VEH_SUBMODEL_SERIES.VEH_ID = VEH.VEH_ID
	LEFT OUTER JOIN VEH_MODIFIER 
		ON VEH.VEH_MODIFIER_ID = VEH_MODIFIER.VEH_MODIFIER_ID
	left outer join body_Style
		on VEH.BODY_STYLE_ID = BODY_STYLE.BODY_STYLE_ID
	inner join Make_Model mm on mm.make_model_id = veh.make_model_id
WHERE mm.[name] = 'Park Avenue' and 
	VEH.MODEL_YR = 2004 AND 
	BODY_STYLE.dsc = '4 Door Sedan' and
	submodel.name = 'Ultra'