CREATE PROCEDURE VT2662AP.GETORDERATTR ( 
	IN ORNO DECIMAL(12, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
BEGIN 
DECLARE C1 CURSOR FOR SELECT * FROM VT2662AFTT . Z3DR503A WHERE TTORNO = ORNO ; 
OPEN C1 ; 
RETURN ; 
END;
